#修改默认端口
server:
  port: 8081

#设置数据源信息
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/student_information?allowMultiQueries=true #?allow...使多条sql语句
    driver-class-name: com.mysql.jdbc.Driver                                   #可以用分号隔开
    username: root
    password: root

#注册mapper映射文件
mybatis-plus:
  mapper-locations: classpath*:com/jxd/student_information/mapper/mapping/*.xml   #扫描mapper.xml文件
  type-aliases-package: com.jxd.student_information.model  #设置别名